spring:
  application:
    name: notificacao-insumos-consumer
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notificacao-email
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false
    admin:
      auto-create: true

server:
  port: 0

app:
  email:
    remetente: posfiapteam35@gmail.com
    senha: jbvp ugel gull ksqr

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: notificacao-insumos-consumer